echo "Testing partner completing job..."
echo "Request ID: 212"
echo ""
echo "Expected: Partner marks job as 'completed'"
echo "Result: Backend should set:"
echo "  - request_status = 'completed'"
echo "  - payment_flow_state = 'waiting_payment'"
echo "  - payment_lock = true"
echo ""
echo "Manual test needed:"
echo "1. Partner app: Press 'Job Done' on request 212"
echo "2. Check database result:"
echo "   SELECT request_status, payment_flow_state, payment_lock"
echo "   FROM requests WHERE id = 212;"
